# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

markdown: kramdown

# Site settings
title: Megazone Noarlunga
email: info@megazone.net.au
description: |
  Megazone Noarlunga is the best events facility around with Laser tag, Drift
  Bumper Cars, Shooting Gallery & Retro Arcades! We specialise in kids
  birthday parties, group bookings, schools, scouts group, sports groups and
  run an awesome laser sporting league!
baseurl: ""
url: http://megazone.net.au
